### ISSUE TITLE
openvpn 现在都可以划时代了？

### ISSUE THREAD

**Issue by NutterChen** [liulilittle/SupersocksR#1]

**Comment by liulilittle** [comment]
谢谢，这仅仅用到了虚拟网卡驱动，现成做好的东西为什么不用？DRY告诉我们不要重复造轮子，如果我们重复造轮子还是类似的虚拟网卡驱动那又有什么意义？。就好比 linux 内核提供了 tun 字符虚拟网卡设备驱动，你不去应用它，而偏偏要重新做一个出来。那么前人开发这些基础轮子的意义何在？是吧。
